name: andrelaiphotography
favicon: null
layout_spectrum: 0.8315640382934362
typography_spectrum: 0.3368302872404456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9895856291987002
  lightness: 0.6572221529204398
  saturation: 0.49807345354929566
  rhythmicContrast: 0.2726275713648647
purpose: []
